// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/27/2026, 10:21:46 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ALSADI/Desktop/Templates/AccountingSystems/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/plugins/**/*.{js,ts,mjs}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/composables/**/*.{js,ts,mjs}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/utils/**/*.{js,ts,mjs}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ALSADI/Desktop/Templates/AccountingSystems/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;